name = "svelteflix"
pages_build_output_dir = ".svelte-kit/cloudflare"
compatibility_date = "2024-05-28"

[env.production]
compatibility_date = "2024-05-28"

[env.production.vars]
PUBLIC_SVELTEFLIX_MEDIA_BASE_API_URL = "https://image.tmdb.org/t/p"
PUBLIC_SVELTEFLIX_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJzdXRsY3hxbXFldG12aXF6Yml6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MjMwNDIwMTgsImV4cCI6MjAzODYxODAxOH0.NOPefpzihrmvjdn1vSiJgeyxsc2RXMyisEjO_glxDvU"
PUBLIC_SVELTEFLIX_SUPABASE_URL = "https://rsutlcxqmqetmviqzbiz.supabase.co"

[env.preview]
compatibility_date = "2024-05-28"

[env.preview.vars]
PUBLIC_SVELTEFLIX_MEDIA_BASE_API_URL = "https://image.tmdb.org/t/p"
PUBLIC_SVELTEFLIX_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJzdXRsY3hxbXFldG12aXF6Yml6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MjMwNDIwMTgsImV4cCI6MjAzODYxODAxOH0.NOPefpzihrmvjdn1vSiJgeyxsc2RXMyisEjO_glxDvU"
PUBLIC_SVELTEFLIX_SUPABASE_URL = "https://rsutlcxqmqetmviqzbiz.supabase.co"
